[install]
registry = "https://registry.npmjs.org"

[test]
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["**/tests/**"]
coverageThreshold = { lines = 0.95, functions = 0.9 }
