[test]
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "**/tests/**",
  "./dist/*",
  "./result/**",
  "../compiler/**",
  "../create/**",
  "../desktop/**",
  "../runtime/**",
  "../schema/**",
  "../server/**",
  "../studio/**",
]
coverageThreshold = { lines = 0.87, functions = 0.88 }
