/**
 * Compile-class.js — Compile .class.json schema-defined classes to JavaScript ES modules
 *
 * Generates proper ES modules with private fields, static members, accessors, etc. from a JSON
 * Schema 2020-12 class definition.
 */

import type {
  JxClassCtorDef,
  JxClassDef,
  JxClassMethodDef,
  JxClassParamDef,
} from "@jxsuite/schema/types";

/**
 * Compile a .class.json schema to a JavaScript ES module string.
 *
 * @param {JxClassDef} classDef - Parsed .class.json content (must have $prototype: "Class")
 * @param {Record<string, unknown>} [_opts]
 * @returns {string} JavaScript module source code
 */
export function compileClassJson(classDef: JxClassDef, _opts: Record<string, unknown> = {}) {
  const className = classDef.title;
  if (!className) {
    throw new Error("compileClassJson: missing title (class name)");
  }

  const baseClass = resolveBaseClass(classDef.extends);
  const defs = classDef.$defs;
  const fields = defs?.fields ?? {};
  // JSON objects inherit Object.prototype.constructor — only an own object value counts.
  const rawCtor = defs?.constructor;
  const ctor = typeof rawCtor === "object" ? rawCtor : undefined;
  const methods = defs?.methods ?? {};

  const lines: string[] = [
    "// Generated by @jxsuite/compiler from .class.json — do not edit manually",
  ];
  if (classDef.$id) {
    lines.push(`// Source: ${classDef.$id}`);
  }
  lines.push("");

  // Class declaration
  const extendsClause = baseClass !== "Object" ? ` extends ${baseClass}` : "";
  lines.push(`class ${className}${extendsClause} {`);

  // Static fields
  for (const [key, f] of Object.entries(fields)) {
    if (f.scope !== "static") {
      continue;
    }
    const name = f.identifier ?? key;
    const prefix = f.access === "private" ? "#" : "";
    const initVal =
      f.initializer !== undefined
        ? JSON.stringify(f.initializer)
        : f.default !== undefined
          ? JSON.stringify(f.default)
          : "null";
    lines.push(`  static ${prefix}${name} = ${initVal};`);
  }

  // Instance field declarations (private)
  for (const [key, f] of Object.entries(fields)) {
    if (f.scope === "static") {
      continue;
    }
    if (f.access !== "private") {
      continue;
    }
    const name = f.identifier ?? key;
    lines.push(`  #${name};`);
  }

  if (Object.keys(fields).length > 0) {
    lines.push("");
  }

  // Constructor
  lines.push("  constructor(config = {}) {");
  if (ctor?.superCall || baseClass !== "Object") {
    const superArgs = ctor?.superCall?.arguments ? ctor.superCall.arguments.join(", ") : "";
    lines.push(`    super(${superArgs});`);
  }

  // Initialize instance fields from config or defaults
  for (const [key, f] of Object.entries(fields)) {
    if (f.scope === "static") {
      continue;
    }
    const name = f.identifier ?? key;
    const prefix = f.access === "private" ? "#" : "";
    const initVal =
      f.initializer !== undefined
        ? JSON.stringify(f.initializer)
        : f.default !== undefined
          ? JSON.stringify(f.default)
          : "null";
    lines.push(
      `    this.${prefix}${name} = config.${name} !== undefined ? config.${name} : ${initVal};`,
    );
  }

  // Constructor body statements
  if (ctor?.body) {
    const bodyLines = Array.isArray(ctor.body) ? ctor.body : [ctor.body];
    for (const line of bodyLines) {
      lines.push(`    ${line}`);
    }
  }
  lines.push("  }");

  // Methods
  for (const [key, m] of Object.entries(methods)) {
    const name = m.identifier ?? key;
    const isStatic = m.scope === "static";
    const isPrivate = m.access === "private";
    const prefix = isPrivate ? "#" : "";
    const staticPrefix = isStatic ? "static " : "";
    const asyncPrefix = m.returnType?.$ref?.includes("Promise") || isMethodAsync(m) ? "async " : "";

    const params = resolveParams(m.parameters ?? []);
    const bodyStr = resolveBody(m.body);

    lines.push("");

    if (m.role === "accessor") {
      // Getter
      if (m.getter) {
        lines.push(`  ${staticPrefix}get ${prefix}${name}() {`, `    ${m.getter.body}`, "  }");
      }
      // Setter
      if (m.setter) {
        const setterParams = resolveParams(m.setter.parameters ?? []);
        lines.push(
          `  ${staticPrefix}set ${prefix}${name}(${setterParams}) {`,
          `    ${m.setter.body}`,
          "  }",
        );
      }
    } else {
      lines.push(`  ${staticPrefix}${asyncPrefix}${prefix}${name}(${params}) {`);
      for (const line of bodyStr) {
        lines.push(`    ${line}`);
      }
      lines.push("  }");
    }
  }

  lines.push("}", "", `export { ${className} };`, `export default ${className};`, "");

  return lines.join("\n");
}

/**
 * Resolve the base class name from an extends value.
 *
 * @param {JxClassDef["extends"]} ext
 * @returns {string}
 */
function resolveBaseClass(ext: JxClassDef["extends"]) {
  if (!ext) {
    return "Object";
  }
  if (typeof ext === "string") {
    return ext;
  }
  if (ext.$ref) {
    const match = ext.$ref.match(/([A-Za-z0-9_]+)\.class\.json/);
    return match ? match[1] : "Object";
  }
  return "Object";
}

/**
 * Resolve parameter names from $ref or inline definitions.
 *
 * @param {JxClassParamDef[]} params
 * @returns {string}
 */
function resolveParams(params: JxClassParamDef[]) {
  return params
    .map((param) => {
      if (param.$ref) {
        return param.$ref.split("/").pop();
      }
      const name = param.identifier ?? param.name;
      return typeof name === "string" ? name : "arg";
    })
    .join(", ");
}

/**
 * Resolve body from string or array of strings.
 *
 * @param {string | string[] | undefined} body
 * @returns {string[]}
 */
function resolveBody(body: string | string[] | undefined) {
  if (!body) {
    return [""];
  }
  return Array.isArray(body) ? body : [body];
}

/**
 * Simple heuristic: does the method body contain await?
 *
 * @param {JxClassMethodDef | JxClassCtorDef} method
 * @returns {boolean}
 */
function isMethodAsync(method: JxClassMethodDef | JxClassCtorDef) {
  const body = Array.isArray(method.body) ? method.body.join("\n") : (method.body ?? "");
  return body.includes("await ");
}
