[test]
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "**/tests/**",
  "./result/**",
  "../collab/**",
  "../compiler/**",
  "../create/**",
  "../desktop/**",
  "../parser/**",
  "../runtime/**",
  "../schema/**",
  "../studio/**",
]
coverageThreshold = { lines = 0.94, functions = 0.84 }
