[test]
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "**/tests/**",
  "./result/**",
  "../ai/**",
  "../collab/**",
  "../compiler/**",
  "../create/**",
  "../desktop/**",
  "../parser/**",
  "../runtime/**",
  "../schema/**",
  "../server/**",
]
coverageThreshold = { lines = 0.89, functions = 0.80 }
