import { describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  assembleWalkthrough,
  concatenateAudio,
  ensureCursorSprite,
  renderFrames,
  walkthroughFrameConcat,
} from "./assemble";
import { silentWav } from "./voice";
import type { CueResult } from "./walkthrough";

async function tmp(): Promise<string> {
  return mkdtemp(join(tmpdir(), "jx-videos-assemble-"));
}

async function ffprobeDuration(path: string): Promise<number> {
  const proc = Bun.spawn(
    ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "json", path],
    { stdout: "pipe" },
  );
  const out = (await new Response(proc.stdout).json()) as { format?: { duration?: string } };
  return Number(out.format?.duration);
}

/** A flat-colored PNG frame, generated by ffmpeg so no binary fixture is committed. */
async function makeFrame(path: string, color: string): Promise<void> {
  const proc = Bun.spawn(
    [
      "ffmpeg",
      "-y",
      "-f",
      "lavfi",
      "-i",
      `color=c=${color}:s=64x36`,
      "-frames:v",
      "1",
      "-update",
      "1",
      path,
    ],
    { stderr: "ignore", stdout: "ignore" },
  );
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`failed to generate test frame ${path}`);
  }
}

describe("walkthroughFrameConcat", () => {
  test("flattens multiple cues' frames into one ffconcat document, in order", () => {
    const cues: CueResult[] = [
      { actualMs: 200, frames: [{ atMs: 0, path: "/a.png" }], overrunMs: 0 },
      { actualMs: 300, frames: [{ atMs: 0, path: "/b.png" }], overrunMs: 0 },
    ];
    const script = walkthroughFrameConcat(cues);
    const order = [...script.matchAll(/file '([^']+)'/g)].map((m) => m[1]);
    expect(order).toEqual(["/a.png", "/b.png", "/b.png"]);
  });
});

describe("ensureCursorSprite", () => {
  test("writes a real PNG", async () => {
    const dir = await tmp();
    try {
      const path = join(dir, "cursor.png");
      await ensureCursorSprite(path);
      const bytes = await Bun.file(path).arrayBuffer();
      const sig = new Uint8Array(bytes.slice(0, 8));
      expect([...sig]).toEqual([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    } finally {
      await rm(dir, { force: true, recursive: true });
    }
  });

  test("is actually cached — a second call does not re-invoke ffmpeg", async () => {
    const dir = await tmp();
    try {
      const path = join(dir, "cursor.png");
      await ensureCursorSprite(path);
      const first = await Bun.file(path).arrayBuffer();
      // Truncate the file to something ffmpeg could never have written, so a real second
      // Invocation would produce a different (valid) byte count. If ensureCursorSprite reads the
      // Cache instead of re-running ffmpeg, the truncated bytes survive untouched.
      await Bun.write(path, new Uint8Array([0x89, 0x50, 0x4e, 0x47]));
      await ensureCursorSprite(path);
      const second = await Bun.file(path).arrayBuffer();
      expect(second.byteLength).toBe(4);
      expect(second.byteLength).not.toBe(first.byteLength);
    } finally {
      await rm(dir, { force: true, recursive: true });
    }
  });
});

describe("renderFrames", () => {
  test("produces a video whose duration is close to the sum of the frame durations", async () => {
    const dir = await tmp();
    try {
      await makeFrame(join(dir, "000000.png"), "red");
      await makeFrame(join(dir, "000001.png"), "green");
      await makeFrame(join(dir, "000002.png"), "blue");
      const cues: CueResult[] = [
        {
          actualMs: 1200,
          frames: [
            { atMs: 0, path: join(dir, "000000.png") },
            { atMs: 500, path: join(dir, "000001.png") },
            { atMs: 900, path: join(dir, "000002.png") },
          ],
          overrunMs: 0,
        },
      ];
      const outPath = join(dir, "video.mp4");
      await renderFrames(cues, 30, dir, outPath);
      const duration = await ffprobeDuration(outPath);
      // A container-level rounding margin, not frame-exact — the same tolerance the plan's own
      // Pacing accepts (ADR-0003 measures the AUDIO exactly; the video is held to it, not the
      // Reverse).
      expect(duration).toBeGreaterThan(1);
      expect(duration).toBeLessThan(1.5);
    } finally {
      await rm(dir, { force: true, recursive: true });
    }
  });
});

describe("concatenateAudio", () => {
  test("concatenates wavs of different lengths into their sum", async () => {
    const dir = await tmp();
    try {
      const a = join(dir, "a.wav");
      const b = join(dir, "b.wav");
      await Bun.write(a, silentWav(0.5));
      await Bun.write(b, silentWav(0.3));
      const out = join(dir, "narration.wav");
      await concatenateAudio([a, b], out);
      const duration = await ffprobeDuration(out);
      expect(duration).toBeCloseTo(0.8, 1);
    } finally {
      await rm(dir, { force: true, recursive: true });
    }
  });

  test("refuses an empty list rather than shelling out to ffmpeg with no input", async () => {
    await expect(concatenateAudio([], "/dev/null")).rejects.toThrow(/no audio files/);
  });
});

describe("assembleWalkthrough", () => {
  test("the three stages compose into one mp4 with both a video and an audio stream", async () => {
    const dir = await tmp();
    try {
      await makeFrame(join(dir, "000000.png"), "red");
      await makeFrame(join(dir, "000001.png"), "blue");
      const cues: CueResult[] = [
        {
          actualMs: 500,
          frames: [
            { atMs: 0, path: join(dir, "000000.png") },
            { atMs: 250, path: join(dir, "000001.png") },
          ],
          overrunMs: 0,
        },
      ];
      const wav = join(dir, "cue-1.wav");
      await Bun.write(wav, silentWav(0.5));
      const outPath = join(dir, "out", "flow.mp4");
      await assembleWalkthrough({
        cacheDir: dir,
        cueResults: cues,
        fps: 30,
        frameDir: dir,
        outPath,
        pointerLog: [{ t: 0.1, x: 10, y: 10 }],
        wavPaths: [wav],
      });
      const proc = Bun.spawn(
        ["ffprobe", "-v", "error", "-show_entries", "stream=codec_type", "-of", "json", outPath],
        { stdout: "pipe" },
      );
      const out = (await new Response(proc.stdout).json()) as {
        streams: { codec_type: string }[];
      };
      const kinds = out.streams.map((s) => s.codec_type).toSorted();
      expect(kinds).toEqual(["audio", "video"]);
    } finally {
      await rm(dir, { force: true, recursive: true });
    }
  });
});
